theme: jekyll-theme-slate
title: "Welcome to Tinkymon's homepage."
description: "This is where i will lay the foundation for the website i will develop: i own the domain http://www.cryptonomisma.com/. Feel free to bookmark it, as I update it."
